"""add category and table_name to assessment_templates

Revision ID: 45379aa62a9f
Revises: 
Create Date: 2025-04-27 11:35:24.571035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45379aa62a9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('table_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_templates', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('table_name')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
