"""Add status and date fields to Assessment

Revision ID: 9fc004d8839d
Revises: 5aad58c857c3
Create Date: 2025-04-27 18:38:42.016449

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9fc004d8839d'
down_revision = '5aad58c857c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('template_20250427_125548')
    op.drop_table('template_20250427_125716')
    op.drop_table('template_20250427_135750')
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.DateTime(), nullable=True))
        batch_op.alter_column('template_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('upload_date')
        batch_op.drop_column('import_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_date', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('upload_date', mysql.DATETIME(), nullable=False))
        batch_op.alter_column('template_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('status')

    op.create_table('template_20250427_135750',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('大类', mysql.TEXT(), nullable=True),
    sa.Column('小类', mysql.TEXT(), nullable=True),
    sa.Column('标准', mysql.TEXT(), nullable=True),
    sa.Column('权重', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('template_20250427_125716',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('大类', mysql.TEXT(), nullable=True),
    sa.Column('小类', mysql.TEXT(), nullable=True),
    sa.Column('标准', mysql.TEXT(), nullable=True),
    sa.Column('权重', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('template_20250427_125548',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('大类', mysql.TEXT(), nullable=True),
    sa.Column('小类', mysql.TEXT(), nullable=True),
    sa.Column('标准', mysql.TEXT(), nullable=True),
    sa.Column('权重', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
