"""add status field to assessment records

Revision ID: c3a83ada2378
Revises: 9fc004d8839d
Create Date: 2025-04-28 10:54:12.579663

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3a83ada2378'
down_revision = '9fc004d8839d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('template_20250428_102341')
    op.drop_table('template_20250428_092744')
    with op.batch_alter_table('assessment_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_records', schema=None) as batch_op:
        batch_op.drop_column('status')

    op.create_table('template_20250428_092744',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('大类', mysql.TEXT(), nullable=True),
    sa.Column('小类', mysql.TEXT(), nullable=True),
    sa.Column('标准', mysql.TEXT(), nullable=True),
    sa.Column('权重', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('template_20250428_102341',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('大类', mysql.TEXT(), nullable=True),
    sa.Column('小类', mysql.TEXT(), nullable=True),
    sa.Column('标准', mysql.TEXT(), nullable=True),
    sa.Column('权重', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
